### PR TITLE
Allow 'carrierwave' dependency to be updated to 0.6.x

### PR DESCRIPTION
**Pull request by d11wtq**
The current gemspec has carrierwave ~> 0.5.8.  This version of carrierwave is giving deprecation warnings due to the use of ActiveSupport::Memoizable, but the newer version has been fixed.  Unfortunately I wasn't able to update carrierwave due to carrierwave-datamapper's gemspec.  I'm not entirely sure what the rules are with the '~> version' notation, but I have just changed it to '>= version' instead.  This gets rid of the warnings we were getting and all the specs pass.

### CODE REVIEW

**Comment by solnic** [comment]
Actually can you make it `~> 0.6.0`?

**Comment by d11wtq** [comment]
No problem, that's done :)

**Comment by d11wtq** [comment]
Hey Piotr, thanks for merging this. Any chance of a push up to rubygems? :)

**Comment by solnic** [comment]
@d11wtq done - just pushed 0.2.1

**Comment by d11wtq** [comment]
Thanks for this! :)

**Pull request merged**
